### ISSUE TITLE
[Feature]: Automatic Resources Deletion 

### ISSUE THREAD

**Issue by Ghiro94** [mia-platform/vab#30]
### Describe the feature

VAB doesn’t have a way to track the resources installed, this way if a resource is removed from the VAB configurations it doesn’t get actually removed from the cluster in the next `vab apply` command. It would be useful whether VAB could keep track of resources managed, in order to keep them in sync with the modules.

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by JGiola** [comment]
Thanks of the suggestions, we will work on it
